version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosmopolitan
    - govet
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - mirror
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - staticcheck
    - tagalign
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    copyloopvar:
      check-alias: true
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enable-all: true
    godot:
      scope: all
    importas:
      no-unaliased: true
    makezero:
      always: true
    misspell:
      locale: US
    nakedret:
      max-func-lines: 5
    nolintlint:
      require-explanation: true
      require-specific: true
    unconvert:
      fast-math: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
